# Generated by Django 6.1.1 on 2026-09-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('padrao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('observacoes', models.TextField()),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudos.medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laudos.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_sistolica', models.IntegerField()),
                ('pressao_diastolica', models.IntegerField()),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('classificacao_pa', models.CharField(blank=True, max_length=50, null=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='laudos.exame')),
                ('status_medicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudos.statusmedicao')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField()),
                ('caminho_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudos.exame')),
                ('template_laudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laudos.templatelaudo')),
            ],
        ),
    ]
